server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springvue?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
  mail:
    host: smtp.yeah.net
    username: Queslime@yeah.net
    password: Queslime123456
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true